on: [pull_request]

name: 'gitlab issue action'
description: 'Moves linked gitlab issue to other column'
inputs:
  branch-name:
    description: 'Branch name, should start with issue id'
    required: true
    default: '0'
  label-to-apply:
    description: 'Label to apply to related issue'
    required: true
    default: 'Code Review'
  gitlab-url:
    description: 'Gitlab Url'
    required: true
    default: 'gitlab.com'
  project-id:
    description: 'Gitlab project id'
    required: true
    default: 0
  access-token:
    description: 'Gitlab Access token'
    required: true
    default: ''
    
runs:
  using: 'node12'
  main: 'dist/index.js'